md ..\..\x86\inc\
copy SmartPtr.h ..\..\x86\inc\
copy SmartArr.h ..\..\x86\inc\
copy SmartHdr.h ..\..\x86\inc\
copy SmartRet.h ..\..\x86\inc\
copy SmartBlk.h ..\..\x86\inc\
copy SmartLck.h ..\..\x86\inc\
copy SmartErr.h ..\..\x86\inc\
copy SmartNal.h ..\..\x86\inc\
copy ShareBlk.h ..\..\x86\inc\
copy Byte.h ..\..\x86\inc\
copy ByteStream.h ..\..\x86\inc\
copy BitStream.h ..\..\x64\inc\
copy Profile.h ..\..\x86\inc\
copy xchar.h ..\..\x86\inc\
copy xevent.h ..\..\x86\inc\
copy xmember.h ..\..\x86\inc\
copy xsemaphore.h ..\..\x86\inc\
copy xstring.h ..\..\x86\inc\
copy xsystem.h ..\..\x86\inc\
copy xthread.h ..\..\x86\inc\
copy xexception.h ..\..\x86\inc\
copy xaid.h ..\..\x86\inc\
copy xutils.h ..\..\x86\inc\
copy os.h ..\..\x86\inc\
copy net.h ..\..\x86\inc\
copy file.h ..\..\x86\inc\
copy ierror.h ..\..\x86\inc\
copy wingetopt.h ..\..\x86\inc\